### ISSUE TITLE
Can't turn on HDR when resuming video

### ISSUE THREAD

**Issue by liu731** [CarterLi/iina#50] opened 2022-05-05 08:36 UTC
**System and IINA version:**

* macOS 12.3.1 (M1 Pro)
* IINA 1.2.0 Build 128 arm64

**Expected behavior:**
HDR can be turned on when resuming video

**Actual behavior:**
Can't turn on HDR when resuming video

**Steps to reproduce:**
1. Open the HDR video for the first time, it is normal at this time
2. Exit IINA
3. Resume the video of step 1, and HDR cannot be turned on at this time (the button is gray)

Interestingly if you want to solve the above problem
1. Clear the playback record and open it again

**How often does this happen?**
Always

**Comment by CarterLi** [comment] 2022-05-05 12:40
Can someone else reproduce this issue?

**Comment by M-Makise-Kurisu** [comment] 2022-05-09 10:06
I can reproduce this issue. But for me I don't need clear the record, completely quit IINA will bring HDR back, for once.
macOS 12.3.1(M1 Max)
IINA 1.2.0 129

**Comment by CarterLi** [comment] 2022-05-09 10:34
So what's the issue for you @M-Makise-Kurisu

**Comment by M-Makise-Kurisu** [comment] 2022-05-09 10:37
> So what's the issue for you @M-Makise-Kurisu

Resume also disable HDR for me

**Comment by CarterLi** [comment] 2022-05-09 11:09
Please record a movie like what I do

https://user-images.githubusercontent.com/6134068/167397990-e663d1a7-c575-4a65-b685-14cb6cf8623a.mp4

**Comment by liu731** [comment] 2022-05-09 11:39
https://user-images.githubusercontent.com/49366127/167402494-62b84927-b723-457e-8d95-3aadd048e477.mov

**Comment by CarterLi** [comment] 2022-05-11 06:01
I can't reproduce your issue with the same steps.

**Comment by M-Makise-Kurisu** [comment] 2022-05-12 15:34
Mine is exactly the same with @liu731

**Comment by space192** [comment] 2022-06-01 22:39
a quick fix for me is to get the slider at the beginning of the video before closing it, when I resume the HDR option re appears again. or if you forgot to bring it back to the beginning when you reopen the video just bring the slider to beginning then close the video and open it again !

**Comment by liu731** [comment] 2022-06-02 02:46
This method works for me. Compared to other videos, HDR videos seem to require more loading/parsing? time, and iina-plus seems to only do this on the first play or at 0:00 timeline. @space192

**Comment by CarterLi** [comment] 2022-06-02 03:03
> This method works for me. Compared to other videos, HDR videos seem to require more loading/parsing? time, and iina-plus seems to only do this on the first play or at 0:00 timeline. @space192

No. I won't bother detecting if it's at 0:00

Because HDR feature has been merged into the official IINA repo, please report theses issues to them to get more duscussions.

**Closed as completed by CarterLi** 2022-06-02 03:03 UTC
